### ISSUE TITLE
TIMEOUT when trying to clear stream . Am i doing something wrong?

### ISSUE THREAD

**Issue by masbaehr** [nats-io/nats.node#424]
Hi, any idea why i'm getting this error when trying to purge a message stream? 

First the output to confirm the stream exists and has messages in it: 
```
connected to 192.168.178.125:4222
 >> jetstream functionality in nats.js is preview functionality 
[
  {
    config: {
      name: 'mystream',
      subjects: [Array],
      retention: 'limits',
      max_consumers: -1,
      max_msgs: -1,
      max_bytes: -1,
      discard: 'old',
      max_age: 0,
      max_msg_size: -1,
      storage: 'file',
      num_replicas: 1,
      duplicate_window: 120000000000
    },
    created: '2021-05-10T19:42:17.234812304Z',
    state: {
      messages: 26,
      bytes: 2486,
      first_seq: 1,
      first_ts: '2021-05-10T19:42:17.244542779Z',
      last_seq: 26,
      last_ts: '2021-05-11T07:11:06.256824968Z',
      consumer_count: 1
    }
  }
]
[ 'subject.one' ]
```

node .\src\nats-clearmessages.js "mystream"

```javascript
const { connect , consumerOpts, createInbox, Empty, StringCodec } = require("nats");

//start with node .\nats-clearmessages MSGID DATASTRING
var myArgs = process.argv.slice(2);
console.log('myArgs: ', myArgs);

const servers = [
   
  { servers: ["192.168.178.125:4222"] },
   
];
servers.forEach(async (v) => {
  try {
    const nc = await connect(v);
    console.log(`connected to ${nc.getServer()}`);
    // this promise indicates the client closed
    const done = nc.closed();
    // do something with the connection

    const  js = nc.jetstream();
    const jsm = await nc.jetstreamManager();

    const stream = myArgs[0];
    console.log("Purging: "+stream);
    jsm.streams.purge(stream);

    // close the connection
    await nc.close();
    // check if the close was OK
    const err = await done;
    if (err) {
      console.log(`error closing:`, err);
    }
  } catch (err) {
      console.log(err);
    console.log(`error connecting to ${JSON.stringify(v)}`);
  }
});
```

```
NatsError: TIMEOUT
    at Function.errorForCode (D:\nats-listener\node_modules\nats\lib\nats-base-client\error.js:98:16)
    at MuxSubscription.close (D:\nats-listener\node_modules\nats\lib\nats-base-client\muxsubscription.js:52:39)
    at ProtocolHandler.<anonymous> (D:\nats-listener\node_modules\nats\lib\nats-base-client\protocol.js:547:35)
    at Generator.next (<anonymous>)
    at D:\nats-listener\node_modules\nats\lib\nats-base-client\protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\nats-listener\node_modules\nats\lib\nats-base-client\protocol.js:4:12)
    at ProtocolHandler._close (D:\nats-listener\node_modules\nats\lib\nats-base-client\protocol.js:538:16)     
    at ProtocolHandler.close (D:\nats-listener\node_modules\nats\lib\nats-base-client\protocol.js:558:21)      
    at NatsConnectionImpl.<anonymous> (D:\nats-listener\node_modules\nats\lib\nats-base-client\nats.js:89:33) {
  code: 'TIMEOUT',
  chainedError: undefined
}
```

**Comment by masbaehr** [comment]
Forget it :/ I noticed myself.. it seems that nc.close() should not be called immediately after issueing purge Sorry

**Comment by aricart** [comment]
@masbaehr or you can await on purge first too.
